baseURL = "https://stefan.lapers.be/"
languageCode = "en-us"
title = "Stefan Lapers"
theme = "hyde-hyde"

highlightjs = false
pygmentsCodefences = true
pygmentsStyle = "friendly"

disqusShortname = "slapers"
googleAnalytics = "UA-70312468-1"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[params]
  authorimage = "/img/stefanlapers_xsmall.jpg"

[params.social]
  github = "slapers"
  twitter = "stefanlapers"
  linkedin = "stefanlapers"
  bitbucket = "slapers"